apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deploy
spec:
  selector:
    matchLabels:
      app: n8n
  template: 
    metadata:          
      labels:
        app: n8n
    spec:            
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep","60"]

---

apiVersion: v1
kind: Service
metadata:
  name: n8n-service
spec:
  selector:
    app: n8n-service
  ports:
  - port: 5678
    targetPort: 5678
  type: LoadBalancer
