apiVersion: v1
kind: Service
metadata:
  name: n8n-service
spec:
  selector:
    app: n8n-service
    type: LoadBalancer
  ports:
      - protocol: TCP
        name: http-svc
        port: 5678
  selector:
      app: n8n
